/*
 *  Globals.h
 *  Somfy
 *
 *  Created by Sempercon on 5/6/11.
 *  Copyright 2011 __Sempercon__. All rights reserved.
 *
 */

//RoomID enums declared as constant
#ifndef __GLOBALS_H
#define __GLOBALS_H

typedef enum ManufacturerIdToNameMapperEnum
{
	ZW_MAN_ZENSYS                         = 0x0000,
	ZW_MAN_ACT                            = 0x0001,
	ZW_MAN_DANFOSS                        = 0x0002,
	ZW_MAN_WRAP                           = 0x0003,
	ZW_MAN_EXHAUSTO                       = 0x0004,
	ZW_MAN_INTERMATIC                     = 0x0005,
	ZW_MAN_INTEL                          = 0x0006,
	ZW_MAN_VIMAR_CRS                      = 0x0007,
	ZW_MAN_WAYNE_DALTON                   = 0x0008,
	ZW_MAN_SYLVANIA                       = 0x0009,
	ZW_MAN_TECHNIKU                       = 0x000A,
	ZW_MAN_CASAWORKS                      = 0x000B,
	ZW_MAN_HOMESEER_TECHNOLOGIES          = 0x000C,
	ZW_MAN_HOME_AUTOMATED_LIVING          = 0x000D,
	ZW_MAN_CONVERGEX_LTD                  = 0x000F,
	ZW_MAN_RCS                            = 0x0010,
	ZW_MAN_ICOM_TECHNOLOGY                = 0x0011,
	ZW_MAN_TELL_IT_ONLINE                 = 0x0012,
	ZW_MAN_INTERNET_DOM                   = 0x0013,
	ZW_MAN_CYBERHOUSE                     = 0x0014,
	ZW_MAN_POWERLYNX                      = 0x0016,
	ZW_MAN_HITECH_AUTOMATION              = 0x0017,
	ZW_MAN_BALBOA_INSTRUMENTS             = 0x0018,
	ZW_MAN_CONTROLTHINK_LC                = 0x0019,
	ZW_MAN_COOPER_WIRING_DEVICES          = 0x001A,
	ZW_MAN_ELK_PRODUCTS                   = 0x001B,
	ZW_MAN_INTELLICON                     = 0x001C,
	ZW_MAN_LEVITON                        = 0x001D,
	ZW_MAN_RYHERD_VENTURES                = 0x001E,
	ZW_MAN_SCIENTIA_TECHNOLOGIES          = 0x001F,
	ZW_MAN_UEI                            = 0x0020,
	ZW_MAN_ZYKRONIX                       = 0x0021,
	ZW_MAN_A1_COMPONENTS                  = 0x0022,
	ZW_MAN_BOCA_DEVICES                   = 0x0023,
	ZW_MAN_LOUDWATER_TECHNOLOGIES         = 0x0025,
	ZW_MAN_BULOGICS                       = 0x0026,
	ZW_MAN_2B_ELECTRONICS                 = 0x0028,
	ZW_MAN_ASIA_HEADING                   = 0x0029,
	ZW_MAN_3E_TECHNOLOGIES                = 0x002A,
	ZW_MAN_ATECH                          = 0x002B,
	ZW_MAN_BESAFER                        = 0x002C,
	ZW_MAN_BROADBAND_ENERGY_NETWORKS_INC  = 0x002D,
	ZW_MAN_CARRIER                        = 0x002E,
	ZW_MAN_COLOR_KINETICS_INCORPORATED    = 0x002F,
	ZW_MAN_CYTECH_TECHNOLOGY_PRE_LTD      = 0x0030,
	ZW_MAN_DESTINY_NETWORKS               = 0x0031,
	ZW_MAN_DIGITAL_5                      = 0x0032,
	ZW_MAN_ELECTRONIC_SOLUTIONS           = 0x0033,
	ZW_MAN_EL_GEV_ELECTRONICS_LTD         = 0x0034,
	ZW_MAN_EMBEDIT                        = 0x0035,
	ZW_MAN_EXCEPTIONAL_INNOVATIONS        = 0x0036,
	ZW_MAN_FOARD_SYSTEMS                  = 0x0037,
	ZW_MAN_HOME_DIRECTOR                  = 0x0038,
	ZW_MAN_HONEYWELL                      = 0x0039,
	ZW_MAN_INLON_SRL                      = 0x003A,
	ZW_MAN_IR_SEC_SAFETY                  = 0x003B,
	ZW_MAN_LIFESTYLE_NETWORKS             = 0x003C,
	ZW_MAN_MARMITEK_BV                    = 0x003D,
	ZW_MAN_MARTEC_ACCESS_PRODUCTS         = 0x003E,
	ZW_MAN_MOTOROLA                       = 0x003F,
	ZW_MAN_NOVAR                          = 0x0040,
	ZW_MAN_OPENPEAK_INC                   = 0x0041,
	ZW_MAN_PRAGMATIC_CONSULTING_INC       = 0x0042,
	ZW_MAN_SENMATIC                       = 0x0043,
	ZW_MAN_SEQUOIA_TECHNOLOGY_LTD         = 0x0044,
	ZW_MAN_SINE_WIRELESS                  = 0x0045,
	ZW_MAN_SMART_PRODUCTS                 = 0x0046,
	ZW_MAN_SOMFY                          = 0x0047,
	ZW_MAN_TELSEY                         = 0x0048,
	ZW_MAN_TWISTHINK                      = 0x0049,
	ZW_MAN_VISUALIZE                      = 0x004A,
	ZW_MAN_WATT_STOPPER                   = 0x004B,
	ZW_MAN_WOODWARD_LABS                  = 0x004C,
	ZW_MAN_XANBOO                         = 0x004D,
	ZW_MAN_ZDATA                          = 0x004E,
	ZW_MAN_ZWAVE_TECHNOLOGIA              = 0x004F,
	ZW_MAN_HOMEPRO                        = 0x0050,
	ZW_MAN_LAGOTEK_CORPORATION            = 0x0051,
	ZW_MAN_HORSTMANN_CONTROLS_LIMITED     = 0x0059,
	ZW_MAN_HOME_AUTOMATED_INC             = 0x005B,
	ZW_MAN_ASPALIS                        = 0x005D,
	ZW_MAN_VIEWSONIC_CORPORATION          = 0x005E,
	ZW_MAN_EVERSPRING                     = 0x0060,
	ZW_MAN_JASCO_PRODUCTS                 = 0x0063,
	ZW_MAN_REITZ_GROUP                    = 0x0064,
	ZW_MAN_RS_SCENE_AUTOMATIO             = 0x0065,
	ZW_MAN_SELUXIT                        = 0x0069,
	ZW_MAN_TRICKLESTAR_LTD                = 0x006B,
	ZW_MAN_HOME_MANAGEBLES                = 0x006F,
	ZW_MAN_LS_CONTROL                     = 0x0071,
	ZW_MAN_INNOVUS                        = 0x0077,
	ZW_MAN_MERTEN                         = 0x007A,
	ZW_MAN_MONSTER_CABLE                  = 0x007E,
	ZW_MAN_LOGITECH                       = 0x007F,
	ZW_MAN_VERO_DUCO                      = 0x0080,
	ZW_MAN_MTC_MAINTRONIC_GERMANY         = 0x0083,
	ZW_MAN_FAKRO                          = 0x0085,
	ZW_MAN_AEON_LABS                      = 0x0086,
	ZW_MAN_EKA_SYSTEMS                    = 0x0087,
	ZW_MAN_TRANE_CORPORATION              = 0x008B,
	ZW_MAN_RARITAN                        = 0x008E,
	ZW_MAN_MB_TURN_KEY_DESIGN             = 0x008F,
	ZW_MAN_KWIKSET                        = 0x0090,
	ZW_MAN_KAMSTRUP                       = 0x0091,
	ZW_MAN_ALARM_DOT_COM                  = 0x0094,
	ZW_MAN_QEES                           = 0x0095,
	ZW_MAN_NORTHQ                         = 0x0096,
	ZW_MAN_GREENWAVE_REALITY_INC          = 0x0099,
	ZW_MAN_HOME_AUTOMATION_EUROPE         = 0x009A,
	ZW_MAN_CAMEO_COMMUNICATIONS_INC       = 0x009C,
	ZW_MAN_COVENTIVE_TECHNOLOGIES_INC     = 0x009D,
	ZW_MAN_EXIGENT_SENSORS                = 0x009F,
	ZW_MAN_ASSA_ABLOY_USA                 = 0x0109
}ManufacturerIdToNameMapperEnum;


static NSString* const NAME_ZENSYS                         = @"Zensys";
static NSString* const NAME_ACT                            = @"Act";
static NSString* const NAME_DANFOSS                        = @"Danfoss";
static NSString* const NAME_WRAP                           = @"Wrap";
static NSString* const NAME_EXHAUSTO                       = @"Exhausto";
static NSString* const NAME_INTERMATIC                     = @"Intermatic";
static NSString* const NAME_INTEL                          = @"Intel";
static NSString* const NAME_VIMAR_CRS                      = @"Vimar CRS";
static NSString* const NAME_WAYNE_DALTON                   = @"Wayne Dalton";
static NSString* const NAME_SYLVANIA                       = @"Sylvania";
static NSString* const NAME_TECHNIKU                       = @"TEchniku";
static NSString* const NAME_CASAWORKS                      = @"Casaworks";
static NSString* const NAME_HOMESEER_TECHNOLOGIES          = @"Homeseer Technologies";
static NSString* const NAME_HOME_AUTOMATED_LIVING          = @"Home Automated Living";
static NSString* const NAME_CONVERGEX_LTD                  = @"Convergex, LTD.";
static NSString* const NAME_RCS                            = @"RCS";
static NSString* const NAME_ICOM_TECHNOLOGY                = @"Icom Technology";
static NSString* const NAME_TELL_IT_ONLINE                 = @"Tell It Online";
static NSString* const NAME_INTERNET_DOM                   = @"Internet Dom";
static NSString* const NAME_CYBERHOUSE                     = @"Cyberhouse";
static NSString* const NAME_POWERLYNX                      = @"Powerlynx";
static NSString* const NAME_HITECH_AUTOMATION              = @"Hitech Automation";
static NSString* const NAME_BALBOA_INSTRUMENTS             = @"Balboa Instruments";
static NSString* const NAME_CONTROLTHINK_LC                = @"ControlThink, LC";
static NSString* const NAME_COOPER_WIRING_DEVICES          = @"Cooper Wiring Devices";
static NSString* const NAME_ELK_PRODUCTS                   = @"Elk Products";
static NSString* const NAME_INTELLICON                     = @"Intellicon";
static NSString* const NAME_LEVITON                        = @"Leviton";
static NSString* const NAME_RYHERD_VENTURES                = @"Ryherd Ventrues";
static NSString* const NAME_SCIENTIA_TECHNOLOGIES          = @"Scientia Technologies";
static NSString* const NAME_UEI                            = @"UEI";
static NSString* const NAME_ZYKRONIX                       = @"Zykronix";
static NSString* const NAME_A1_COMPONENTS                  = @"A1 Components";
static NSString* const NAME_BOCA_DEVICES                   = @"Boca Devices";
static NSString* const NAME_LOUDWATER_TECHNOLOGIES         = @"Loudwater Technologies";
static NSString* const NAME_BULOGICS                       = @"Bulogics";
static NSString* const NAME_2B_ELECTRONICS                 = @"2B Electronics";
static NSString* const NAME_ASIA_HEADING                   = @"Asia Heading";
static NSString* const NAME_3E_TECHNOLOGIES                = @"3e Technologies";
static NSString* const NAME_ATECH                          = @"Atech";
static NSString* const NAME_BESAFER                        = @"Besafer";
static NSString* const NAME_BROADBAND_ENERGY_NETWORKS_INC  = @"Broadband Energy Networks, Inc";
static NSString* const NAME_CARRIER                        = @"Carrier";
static NSString* const NAME_COLOR_KINETICS_INCORPORATED    = @"Color Kinetics Incorporated";
static NSString* const NAME_CYTECH_TECHNOLOGY_PRE_LTD      = @"Cytech Technology Pre, LTD";
static NSString* const NAME_DESTINY_NETWORKS               = @"Destiny Networks";
static NSString* const NAME_DIGITAL_5                      = @"Digital 5";
static NSString* const NAME_ELECTRONIC_SOLUTIONS           = @"Electronic Solutions";
static NSString* const NAME_EL_GEV_ELECTRONICS_LTD         = @"El Gev Electronics, LTD";
static NSString* const NAME_EMBEDIT                        = @"Embedit";
static NSString* const NAME_EXCEPTIONAL_INNOVATIONS        = @"Exeptional Innovations";
static NSString* const NAME_FOARD_SYSTEMS                  = @"Foard Systems";
static NSString* const NAME_HOME_DIRECTOR                  = @"Home Director";
static NSString* const NAME_HONEYWELL                      = @"Honeywell";
static NSString* const NAME_INLON_SRL                      = @"Inlon, SRL";
static NSString* const NAME_IR_SEC_SAFETY                  = @"IR SEC Safety";
static NSString* const NAME_LIFESTYLE_NETWORKS             = @"Lifestyle Networks";
static NSString* const NAME_MARMITEK_BV                    = @"Marmitek, BV";
static NSString* const NAME_MARTEC_ACCESS_PRODUCTS         = @"Martec Access Products";
static NSString* const NAME_MOTOROLA                       = @"Motorola";
static NSString* const NAME_NOVAR                          = @"Novar";
static NSString* const NAME_OPENPEAK_INC                   = @"Openpeak, Inc";
static NSString* const NAME_PRAGMATIC_CONSULTING_INC       = @"Pragmatic Consulting";
static NSString* const NAME_SENMATIC                       = @"Senmatic";
static NSString* const NAME_SEQUOIA_TECHNOLOGY_LTD         = @"Sequoia Technology, LTD";
static NSString* const NAME_SINE_WIRELESS                  = @"Sine Wireless";
static NSString* const NAME_SMART_PRODUCTS                 = @"Smart Products";
static NSString* const NAME_SOMFY                          = @"Somfy";
static NSString* const NAME_TELSEY                         = @"Telsey";
static NSString* const NAME_TWISTHINK                      = @"Twisthink";
static NSString* const NAME_VISUALIZE                      = @"Visualize";
static NSString* const NAME_WATT_STOPPER                   = @"Watt Stopper";
static NSString* const NAME_WOODWARD_LABS                  = @"Woodward Labs";
static NSString* const NAME_XANBOO                         = @"Xanboo";
static NSString* const NAME_ZDATA                          = @"Zdata";
static NSString* const NAME_ZWAVE_TECHNOLOGIA              = @"ZWave Technologia";
static NSString* const NAME_HOMEPRO                        = @"Homepro";
static NSString* const NAME_LAGOTEK_CORPORATION            = @"Lagotek Corporation";
static NSString* const NAME_HORSTMANN_CONTROLS_LIMITED     = @"Horstmann Controls Limited";
static NSString* const NAME_HOME_AUTOMATED_INC             = @"Home Automated Inc";
static NSString* const NAME_ASPALIS                        = @"Aspalis";
static NSString* const NAME_VIEWSONIC_CORPORATION          = @"Viewsonic Corporation";
static NSString* const NAME_EVERSPRING                     = @"Everspring";
static NSString* const NAME_JASCO_PRODUCTS                 = @"Jasco Products";
static NSString* const NAME_REITZ_GROUP                    = @"Reitz Group";
static NSString* const NAME_RS_SCENE_AUTOMATION            = @"RS Scene Automation";
static NSString* const NAME_SELUXIT                        = @"Seluxit";
static NSString* const NAME_TRICKLESTAR_LTD                = @"Tricklestar, LTD";
static NSString* const NAME_HOME_MANAGEBLES                = @"Home Managebles";
static NSString* const NAME_LS_CONTROL                     = @"LS Control";
static NSString* const NAME_INNOVUS                        = @"Innovus";
static NSString* const NAME_MERTEN                         = @"Merten";
static NSString* const NAME_MONSTER_CABLE                  = @"Monster Cable";
static NSString* const NAME_LOGITECH                       = @"Logitech";
static NSString* const NAME_VERO_DUCO                      = @"Vero Duco";
static NSString* const NAME_MTC_MAINTRONIC_GERMANY         = @"MTC Maintronic Germany";
static NSString* const NAME_FAKRO                          = @"Fakro";
static NSString* const NAME_AEON_LABS                      = @"Aeon Labs";
static NSString* const NAME_EKA_SYSTEMS                    = @"EKA Systems";
static NSString* const NAME_TRANE_CORPORATION              = @"Trane Corporation";
static NSString* const NAME_RARITAN                        = @"Raritan";
static NSString* const NAME_MB_TURN_KEY_DESIGN             = @"MB Turn Key Design";
static NSString* const NAME_KWIKSET                        = @"Kwikset";
static NSString* const NAME_KAMSTRUP                       = @"Kamstrup";
static NSString* const NAME_ALARM_DOT_COM                  = @"Alarm Dot Com";
static NSString* const NAME_QEES                           = @"QEES";
static NSString* const NAME_NORTHQ                         = @"Northq";
static NSString* const NAME_GREENWAVE_REALITY_INC          = @"Greenwave Reality, Inc";
static NSString* const NAME_HOME_AUTOMATION_EUROPE         = @"Home Automation Europe";
static NSString* const NAME_CAMEO_COMMUNICATIONS_INC       = @"Cameo Communications, Inc";
static NSString* const NAME_COVENTIVE_TECHNOLOGIES_INC     = @"Conventive Technologies, Inc";
static NSString* const NAME_EXIGENT_SENSORS                = @"Exigent Sensors";	
static NSString* const NAME_ASSA_ABLOY_USA                 = @"Assa Abloy, USA";


static NSString* const UNKNOWN_STRING=@"Unknown";
static NSString* const CONTROLLER_STRING=@"Controller";
static NSString* const MULTILEVEL_SWITCH_STRING=@"MultiLevel Switch";
static NSString* const BINARY_SWITCH_STRING=@"Binary Switch";
static NSString* const UNDEFINED_STRING=@"Undefined";
static NSString* const THERMOSTAT_STRING=@"Thermostat";
static NSString* const THERMOSTATV2_STRING=@"Thermostat";
static NSString* const SETBACK_THERMOSTAT_STRING=@"SetBack Thermostat";
static NSString* const GARAGE_DOOR_STRING=@"Garage door";
static NSString* const SATELLITE_RADIO_STRING=@"Satellite Radio";
static NSString* const BINARY_SENSOR_STRING=@"Binary Sensor";
static NSString* const BINARY_SENSOR_TWO_STRING=@"Binary Sensor";
//static NSString* const UNDEFINED=12;
//static NSString* const UNDEFINED=13;
//static NSString* const UNDEFINED=14;
//static NSString* const UNDEFINED=15;
static NSString* const PC_CONTROLLER_STRING=@"PC Controller";
static NSString* const STATIC_CONTROLLER_STRING=@"Static Controller";
static NSString* const SCENE_CONTROLLER_STRING=@"Scene Controller";
static NSString* const SCENE_CONTROLLER_PORTABLE_STRING=@"Portable Scene Controller";
static NSString* const SCENE_CONTROLLER_TWO_STRING=@"Scene Controller";
static NSString* const INSTALLER_TOOL_STRING=@"Installer Tool";
static NSString* const INSTALLER_TOOL_PORTABLE_STRING=@"Portable Installer Tool";
static NSString* const REMOTE_CONTROLLER_PORTABLE_STRING=@"Portable Remote Controller";

static NSString* const METER_GENERIC_STRING=@"Generic Meter";
static NSString* const REMOTE_SWITCH_STRING=@"Remote Switch";
static NSString* const MULTILEVEL_SENSOR_STRING=@"Multilevel Sensor";
static NSString* const ENTRY_CONTROL_STRING=@"Entry Control";
static NSString* const SECURE_KEYPAD_ENTRY_CONTROL_DOOR_LOCK_STRING=@"Secure Keypad Entry Control";
static NSString* const ADVANCED_ENTRY_CONTROL_DOOR_LOCK_STRING=@"Advanced entry control door lock";
static NSString* const BULOGICS_USB_SHUTDOWN_STICK_STRING=@"Bulogcs USB Shutdown Stick";
static NSString* const ZIGBEE_METER_STRING=@"Zigbee Meter";
static NSString* const THERMOSTAT_RCS_STRING=@"Thermostat RCS";
static NSString* const SCENE_CONTROLLER_THREE_STRING=@"Scene Controller";
static NSString* const ZONE_CONTROLLER_STRING=@"Zone Controller";
static NSString* const SOMFY_ILT_STRING=@"Somfy LTS";
static NSString* const SOMFY_RTS_STRING=@"Somfy RTS Bridge";



#endif

